apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 'llm-gateway'
  description: 'LLM Gateway'
spec:
  # See Backstage documentation to read more information on types and lifecycles
  # https://github.com/wealthsimple/backstage-app/blob/main/docs/how-to/manage-catalog-files.md#entity-kinds--types
  type: 'service'
  lifecycle: experimental
